AWSTemplateFormatVersion: "2010-09-09"
Description: Exposes S3 Rest API via API Gateway

Parameters:
  s3apiGatewayStageName:
    Type: "String"
    AllowedPattern: "^[a-z0-9]+$"
    Default: "dev"    

  s3apiGatewayExecRoleName:
    Type: "String"
    Default: "s3ApiGateWayExecutionRole"

  s3apiGatewaySwaggerBucketName:
    Type: String
    Description: Bucket where S3 API Swagger file is stored

  s3ApiGatewaySwaggerFileName:
    Type: String
    Description: Swagger File Name (Key name) that is stored in the bucket above

Resources:
  s3ApiGatewayExecRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "apigateway.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      RoleName: !Ref s3apiGatewayExecRoleName

  s3ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      ApiKeySourceType: HEADER
      Body: 
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub "s3://${s3apiGatewaySwaggerBucketName}/${s3ApiGatewaySwaggerFileName}"
      FailOnWarnings: True
      MinimumCompressionSize: 0
      Name: S3API

  s3ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: s3ApiGateway
    Properties:
      Description: S3 API Deployment
      RestApiId: !Ref s3ApiGateway
      StageName: !Ref s3apiGatewayStageName

  s3ApiGatewayApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: s3ApiGatewayDeployment
    Properties:
      Description: A basic key for restricting access to the S3 API
      Name: basicKeyForS3API
      Enabled: True

  s3ApiGatewayUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: s3ApiGatewayApiKey
    Properties:
      Description: A basic usage plan for S3 API
      UsagePlanName: basicPlanForS3API      
      ApiStages:
        - ApiId: !Ref s3ApiGateway
          Stage: !Ref s3apiGatewayStageName
      Quota:
        Limit: 1000
        Period: DAY
      Throttle:
        BurstLimit: 20
        RateLimit: 5

  s3ApiGatewayUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn: s3ApiGatewayUsagePlan
    Properties:
      KeyId: !Ref s3ApiGatewayApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref s3ApiGatewayUsagePlan

Outputs:
  s3apiGatewayInvokeURL:
    Description: Invoke URL of the S3 API
    Value: !Sub "https://${s3ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${s3apiGatewayStageName}" 

